// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_2OecVxBjDa850MU8F-9pk2F2nlgaD0',
    appId: '1:500442120800:web:4c34dc0103473732a87905',
    messagingSenderId: '500442120800',
    projectId: 'ocakfirebase',
    authDomain: 'ocakfirebase.firebaseapp.com',
    storageBucket: 'ocakfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7sZhq6yJYVhZMHzYc3MXEpi2MHR8mN50',
    appId: '1:500442120800:android:0fc1b7c68a8ae5bea87905',
    messagingSenderId: '500442120800',
    projectId: 'ocakfirebase',
    storageBucket: 'ocakfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsLQGXKwcFi-YqyIB240o_xS6XT1xU0Ro',
    appId: '1:500442120800:ios:4098a97ea86fa7b0a87905',
    messagingSenderId: '500442120800',
    projectId: 'ocakfirebase',
    storageBucket: 'ocakfirebase.firebasestorage.app',
    iosBundleId: 'com.turgut.firebaseBaslangic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsLQGXKwcFi-YqyIB240o_xS6XT1xU0Ro',
    appId: '1:500442120800:ios:4098a97ea86fa7b0a87905',
    messagingSenderId: '500442120800',
    projectId: 'ocakfirebase',
    storageBucket: 'ocakfirebase.firebasestorage.app',
    iosBundleId: 'com.turgut.firebaseBaslangic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK_2OecVxBjDa850MU8F-9pk2F2nlgaD0',
    appId: '1:500442120800:web:a5e019b860e709b1a87905',
    messagingSenderId: '500442120800',
    projectId: 'ocakfirebase',
    authDomain: 'ocakfirebase.firebaseapp.com',
    storageBucket: 'ocakfirebase.firebasestorage.app',
  );

}